apiVersion: v1
kind: ConfigMap
metadata:
  name: graylog-master-config
  namespace: logging
data:
  mongodb_uri: mongodb://mongo-graylog-0.mongo-graylog.logging.svc.cluster.local:27017,mongo-graylog-1.mongo-graylog.logging.svc.cluster.local:27017,mongo-graylog-2.mongo-graylog.logging.svc.cluster.local:27017/graylog?replicaSet=rs0
  is_master: 'true'
  elasticsearch_hosts: https://vpc-graylog-prod-uazovty6jvwvezxrgtlktw3swm.us-west-2.es.amazonaws.com
  rest_listen_uri: http://0.0.0.0:9000/api/
  web_listen_uri: http://0.0.0.0:9000/
  web_endpoint_uri: https://graylog.infra.iam.mozilla.com/api/
  server_java_opts: -Xms1024m -Xmx1024m -XX:NewRatio=1 -XX:MaxMetaspaceSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow

